import {
  ArrowLeft,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  ClipboardList,
  Menu,
  MoreHorizontal,
  Settings,
  ShoppingBasket,
  ShoppingCart,
  Star,
  Wrench,
  X,
} from "lucide-react";

export const Icon = {
  Menu: Menu,
  X: X,
  ArrowLeft: ArrowLeft,
  MoreHorizontal: MoreHorizontal,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronsLeft: ChevronsLeft,
  ChevronsRight: ChevronsRight,
  ShoppingCart: ShoppingCart,
  ShoppingBasket: ShoppingBasket,
  Star: Star,
  ClipboardList: ClipboardList,
  Settings: Settings,
  Wrench: Wrench,
};
