import {
  ArrowLeft,
  BookOpen,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleDollarSign,
  ClipboardList,
  Construction,
  CreditCard,
  Home,
  Instagram,
  Menu,
  MoreHorizontal,
  Settings,
  ShoppingBasket,
  ShoppingCart,
  Star,
  Wrench,
  X,
  Youtube,
} from "lucide-react";

export const Icon = {
  Menu: Menu,
  X: X,
  ArrowLeft: ArrowLeft,
  MoreHorizontal: MoreHorizontal,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronsLeft: ChevronsLeft,
  ChevronsRight: ChevronsRight,
  ShoppingCart: ShoppingCart,
  ShoppingBasket: ShoppingBasket,
  Star: Star,
  ClipboardList: ClipboardList,
  Settings: Settings,
  Wrench: Wrench,
  Instagram: Instagram,
  Youtube: Youtube,
  CreditCard: CreditCard,
  CircleDollarSign: CircleDollarSign,
  BookOpen: BookOpen,
  Home: Home,
  Construction: Construction,
};
